export const SIGN_IN_RESPONSE_OK = 'SIGN_IN_RESPONSE_OK'
export const SIGN_IN_RESPONSE_VALIDATION_DATA = 'SIGN_IN_RESPONSE_VALIDATION_DATA'
export const SIGN_IN_RESPONSE_CHANGE_PASSWORD = 'SIGN_IN_RESPONSE_CHANGE_PASSWORD'
export const SIGN_IN_RESPONSE_SOFTWARE_TOKEN_MFA = 'SIGN_IN_RESPONSE_SOFTWARE_TOKEN_MFA'
export const SIGN_IN_RESPONSE_USER_NOT_FOUND = 'SIGN_IN_RESPONSE_USER_NOT_FOUND'
export const SIGN_IN_RESPONSE_NOT_CONFIRMED = 'SIGN_IN_RESPONSE_NOT_CONFIRMED'
export const SIGN_IN_RESPONSE_NOT_AUTHORIZED = 'SIGN_IN_RESPONSE_NOT_AUTHORIZED'

// FIXME remove the RESPONSE label
export const CONFIRM_SIGN_UP_RESPONSE_OK = 'CONFIRM_SIGN_UP_RESPONSE_OK'
export const CONFIRM_SIGN_UP_CODE_MISMATCH = 'CONFIRM_SIGN_UP_CODE_MISMATCH'
export const CONFIRM_SIGN_UP_USER_NOT_FOUND = 'CONFIRM_SIGN_UP_USER_NOT_FOUND'
export const CONFIRM_SIGN_UP_EXPIRED_CODE = 'CONFIRM_SIGN_UP_EXPIRED_CODE'
export const CONFIRM_SIGN_UP_ERROR = 'CONFIRM_SIGN_UP_ERROR'

export const RESEND_VALIDATION_CODE_RESPONSE_OK = 'RESEND_VALIDATION_CODE_RESPONSE_OK'
export const RESEND_VALIDATION_CODE_RESPONSE_ERROR = 'RESEND_VALIDATION_CODE_RESPONSE_ERROR'

export const RESEND_VALIDATION_CODE_STATE_NOT_REQUESTED = 'NOT_REQUESTED'
export const RESEND_VALIDATION_CODE_STATE_SENDING = 'SENDING'
export const RESEND_VALIDATION_CODE_STATE_SENDING_SUCCESS = 'SENDING_SUCCESS'
export const RESEND_VALIDATION_CODE_STATE_SENDING_ERROR = 'SENDING_ERROR'

export const CHANGE_PASSWORD_FORCED_USER_NOT_FOUND = 'USER_NOT_FOUND'
export const CHANGE_PASSWORD_FORCED_INVALID_PASSWORD = 'INVALID_PASSWORD'
export const CHANGE_PASSWORD_FORCED_ERROR = 'ERROR'

